# Generated by Django 2.2.2 on 2019-07-31 15:13

import authentification.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(error_messages={'unique': "n'est pas disponible"}, max_length=127, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_type', models.IntegerField(choices=[(0, 'Admin'), (1, 'Staff'), (2, 'Moderator'), (3, 'User'), (4, 'Guest')], default=3)),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', authentification.models.MyUserManager()),
            ],
        ),
    ]
