# Generated by Django 2.2.2 on 2019-08-01 16:43

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190801_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=djongo.models.fields.ListField(default=[]),
        ),
    ]
