# Generated by Django 2.2.2 on 2019-08-01 17:19

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190801_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='score',
            new_name='scoreKeys',
        ),
        migrations.AddField(
            model_name='submission',
            name='scoreValues',
            field=djongo.models.fields.ListField(default=[]),
        ),
    ]
