# Generated by Django 2.2.2 on 2019-08-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20190801_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='scoreKeys',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='scoreValues',
        ),
    ]
