export const GET_USERS = "GET_USERS";
export const CHALLENGE_SELECTED = "CHALLENGE_SELECTED";
export const FETCH_CHALLENGES = "FETCH_CHALLENGES";
export const FETCH_COURSES = "FETCH_COURSES";


export const FETCH_NON_ENROLLED = "FETCH_NON_ENROLLED";
export const FETCH_NON_ENROLLED_FAIL = "FETCH_NON_ENROLLED_FAIL";

export const FETCH_ENROLLED = "FETCH_ENROLLED";
export const FETCH_ENROLLED_FAIL = "FETCH_ENROLLED_FAIL";
export const ENROLL_USER = "ENROLL_USER";
export const REMOVE_ENROLLMENT = "REMOVE_ENROLLMENT";


export const FETCH_NON_MANAGER = "FETCH_NON_MANAGER";
export const FETCH_NON_MANAGER_FAIL = "FETCH_NON_MANAGER_FAIL";

export const FETCH_MANAGER = "FETCH_MANAGER";
export const FETCH_MANAGER_FAIL = "FETCH_MANAGER_FAIL";
export const REMOVE_MANAGER = "REMOVE_MANAGER";

export const REMOVE_CHALLENGE = "REMOVE_CHALLENGE";
export const SWITCH_VISIBILITY = "SWITCH_VISIBILITY";
export const SWITCH_SUBMISSION_DELETE = "SWITCH_SUBMISSION_DELETE";
export const SWITCH_GROUP_EDIT = "SWITCH_GROUP_EDIT";

export const ADD_TO_GROUP = "ADD_TO_GROUP";
export const FETCH_NON_GROUPED = "FETCH_NON_GROUPED";
export const FETCH_NON_GROUPED_FAIL = "FETCH_NON_GROUPED_FAIL";

export const ADD_MANAGER = "ADD_MANAGER";

export const WAIT_ASK = "WAIT_ASK";
export const WAIT_FINISH = "WAIT_FINISH";

export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const ADD_COURSE = 'ADD_COURSE';
export const ADD_COURSE_FAIL = 'ADD_COURSE_FAIL';
export const ADD_CHALLENGE = 'ADD_CHALLENGE';
export const ADD_CHALLENGE_FAIL = 'ADD_CHALLENGE_FAIL';
export const INFORMATIONS_UPDATED = 'INFORMATIONS_UPDATED'

export const CREATE_SUBMISSION = 'CREATE_SUBMISSION'
export const FETCH_SUBMISSION = 'FETCH_SUBMISSION'
export const FETCH_GROUP = 'FETCH_GROUP'
export const CREATE_GROUP = 'CREATE_GROUP'
export const REMOVE_GROUP = 'REMOVE_GROUP'
export const REMOVE_SUBMISSION = 'REMOVE_SUBMISSION'


